# This is the makefile for these tutorials

all: fork exec_1 exec_2 fork_exec

fork: fex1.c
	gcc -o fork.out fex1.c
exec_1: ex1.c
	gcc -o exec_1.out ex1.c
exec_2: ex1.c
	gcc -o exec_2.out ex2.c
fork_exec:
	gcc -o fork_exec.out fork_exec.c
clean:
	rm -rf fork